resources:
  # Sample Go app in a GitRepo
  - name: go_example
    type: GitRepo
    configuration:
      path: raksha78/jfrog-pipelines-go-sample
      branches:
        include: dev
      gitProvider: rak_github
       
  # Build info for the published Go module
  - name: go_build_info_publish_module
    type: BuildInfo
    configuration:
      sourceArtifactory: rak_art
       
  # Build info for the published Go app
  - name: go_build_info_publish
    type: BuildInfo
    configuration:
      sourceArtifactory: rak_art

pipelines:
  - name: go_build_pipeline_example_rak
    steps:
      # Build the Go sample app from the GitRepo
      - name: build_go
        type: GoBuild
        configuration:
          environmentVariables:
            JFROG_CLI_BUILD_NAME: go_example_build_publish
          sourceLocation: .
          repository: go_local
          outputLocation: /tmp/dist
          outputFile: hello_gb
          inputResources:
            - name: go_example
          integrations:
            - name: rak_art
             
      # Publish the Go sample app binary to Artifactory
      - name: publish_go_binary
        type: GoPublishBinary
        configuration:
          inputSteps:
            - name: build_go
          targetRepository: go_local
          integrations:
            - name: rak_art
             
      # Publish the Go sample app build info
      - name: publish_build
        type: PublishBuildInfo
        configuration:
          inputSteps:
            - name: publish_go_binary
          outputResources:
            - name: go_build_info_publish
             
      # Publish the Go module from the GitRepo
      - name: publish_go_module
        type: GoPublishModule
        configuration:
          environmentVariables:
            JFROG_CLI_BUILD_NAME: go_example_module_publish
          sourceLocation: .
          version: v0.0.0
          targetRepository: go_local
          autoPublishBuildInfo: true
          integrations:
            - name: rak_art
          inputResources:
            - name: go_example
          outputResources:
            - name: go_build_info_publish_module
